// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEf8RquwoOVkoX5DHPiTaEnyUXPF0Joy0',
    appId: '1:572274556964:web:4a5230f2c0f2f294e718b1',
    messagingSenderId: '572274556964',
    projectId: 'agendav2-aed86',
    authDomain: 'agendav2-aed86.firebaseapp.com',
    databaseURL: 'https://agendav2-aed86-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'agendav2-aed86.appspot.com',
    measurementId: 'G-Z1CPZWH8C6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkfiBdC99cz07_k8-f6CCfgtFGXWX91iE',
    appId: '1:572274556964:android:9ffb8073c203a694e718b1',
    messagingSenderId: '572274556964',
    projectId: 'agendav2-aed86',
    databaseURL: 'https://agendav2-aed86-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'agendav2-aed86.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCK-TXL8huVH_xHMVyxx7qnXX0JEnGdDGw',
    appId: '1:572274556964:ios:44e099651c2b000de718b1',
    messagingSenderId: '572274556964',
    projectId: 'agendav2-aed86',
    databaseURL: 'https://agendav2-aed86-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'agendav2-aed86.appspot.com',
    iosClientId: '572274556964-v4kc1qgdg1uf7af5sk8al7dqi43q5omo.apps.googleusercontent.com',
    iosBundleId: 'com.example.agendaV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCK-TXL8huVH_xHMVyxx7qnXX0JEnGdDGw',
    appId: '1:572274556964:ios:44e099651c2b000de718b1',
    messagingSenderId: '572274556964',
    projectId: 'agendav2-aed86',
    databaseURL: 'https://agendav2-aed86-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'agendav2-aed86.appspot.com',
    iosClientId: '572274556964-v4kc1qgdg1uf7af5sk8al7dqi43q5omo.apps.googleusercontent.com',
    iosBundleId: 'com.example.agendaV2',
  );
}
